name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build and distribute
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Gradle Cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: decode google-service
      env:
        GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
      run: echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > ./app/google-services.json

    - name: generateAPK
      run: ./gradlew assembleDebug
      env:
        OAUTH_CONSUMERKEY: ${{ secrets.OAUTH_CONSUMERKEY }}
        OAUTH_CONSUMERSECRET: ${{ secrets.OAUTH_CONSUMERSECRET }}

    - name: Distribute App
      run: |
       curl \
        -H "Authorization: token ${{secrets.DEPLOYGATE_API_KEY}}" \
        -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
        -F "message=`git log -1 --pretty='%s' $GITHUB_SHA`" \
        "https://deploygate.com/api/users/${{secrets.DEPLOYGATE_USER}}/apps"
